import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="min-h-screen px-12 md:px-48 mx-auto w-[64rem] flex flex-col overflow-hidden">
        <header className="flex items-center justify-between mt-4 mb-12">
          <Link href="/">
            <h1>Crazy Eights Countdown</h1>
          </Link>
          {/* <p className="text-blue-400">Selecting players</p> */}
        </header>
        <main className="relative flex flex-col flex-grow mb-4">
          {children}
        </main>
      </body>
    </html>
  );
}
