import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen px-12 md:px-48 mx-auto w-[64rem] flex flex-col">
        <header className="flex justify-between items-center mb-12 mt-4">
          <Link href="/">
            <h1>Crazy Eights Countdown</h1>
          </Link>
          {/* <p className="text-blue-400">Selecting players</p> */}
        </header>
        <main className="flex-grow flex flex-col mb-4">{children}</main>
      </body>
    </html>
  );
}
